### API - Application Programming Interface

In [4]:
import requests

In [6]:
URL = "https://stephen-king-api.onrender.com/api/books"

res = requests.get(URL)

In [14]:
json_data = res.json()

In [17]:
import pandas as pd

df = pd.json_normalize(json_data["data"])
df[["id","Title","Year"]]

    id          Title  Year
0    1         Carrie  1974
1    2    Salem's Lot  1975
2    3    The Shining  1977
3    4           Rage  1977
4    5      The Stand  1978
..  ..            ...   ...
58  59   The Outsider  2018
59  60      Elevation  2018
60  61  The Institute  2019
61  62          Later  2021
62  63  Billy Summers  2021

[63 rows x 3 columns]

--->> HomeWork <<---

In [23]:
URL2 = "https://api.thecatapi.com/v1/images/search?limit=10"

response = requests.get(URL2)
response

In [26]:
data = response.json()


df = pd.json_normalize(data)
df[["id","url"]]

           id                                               url
0          kc          https://cdn2.thecatapi.com/images/kc.jpg
1         2eq         https://cdn2.thecatapi.com/images/2eq.jpg
2         8kf         https://cdn2.thecatapi.com/images/8kf.jpg
3         905         https://cdn2.thecatapi.com/images/905.jpg
4         a2d         https://cdn2.thecatapi.com/images/a2d.jpg
5         cce         https://cdn2.thecatapi.com/images/cce.jpg
6         cki         https://cdn2.thecatapi.com/images/cki.jpg
7         dgg         https://cdn2.thecatapi.com/images/dgg.jpg
8  MTYyNjY5Ng  https://cdn2.thecatapi.com/images/MTYyNjY5Ng.jpg
9  MjA3NDMzMg  https://cdn2.thecatapi.com/images/MjA3NDMzMg.jpg

--->> HomeWork <<---

In [28]:
URL3 = "https://dogapi.dog/api-docs/v2/swagger.json"

res3 = requests.get(URL3)
res3

In [30]:
data = res3.json()

df = pd.json_normalize(data)
df

,openapi,servers,info.title,info.version,info.description,info.termsOfService,info.contact.email,info.license.name,info.license.url,paths./breeds.get.summary,...,paths./groups/{id}.get.summary,paths./groups/{id}.get.tags,paths./groups/{id}.get.parameters,paths./groups/{id}.get.responses.200.description,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.id,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.type,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.attributes.name,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.data.relationships.breeds.data,paths./groups/{id}.get.responses.200.content.application/json.examples.example.value.links.self,paths./groups/{id}.get.responses.404.description
0,3.0.1,[{'url': 'https://dogapi.dog/api/v2'}],API V2,1.0.0,The Dog API provides a wealth of information o...,https://dogapi.dog/terms,dev@dogapi.dog,MIT,https://github.com/kinduff/dogapi.dog/blob/mas...,list breeds,...,get group with non-existing id,[Groups],"[{'name': 'id', 'in': 'path', 'required': True...",successful,02124eb6-1baa-410c-90ea-6b8629fb0837,group,Foundation Stock Service,[{'id': 'b0b6810c-fb88-4987-ad0a-ae0440b04634'...,https://dogapi.dog/api/v2/groups/02124eb6-1baa...,not-found